name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Docker Compose
        uses: docker/setup-qemu-action@v2

      - name: Ensure docker compose is available
        run: docker-compose version

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Run integration script
        run: npm run test:integration
